#Ce fichier contiens la config de base du serveur---
Infos:
    1:
        message: Image de démo à modifier dans votre panel CraftMyWebsite ! (1)
        image: miniature-demo-1.jpg
        lien: '#'
    2:
        message: Image de démo à modifier dans votre panel CraftMyWebsite ! (2)
        image: miniature-demo-2.jpg
        lien: '#'
    3:
        message: Image de démo à modifier dans votre panel CraftMyWebsite ! (3)
        image: miniature-demo-3.jpg
        lien: '#'
    4:
        message: Image de démo à modifier dans votre panel CraftMyWebsite ! (4)
        image: miniature-demo-1.png
        lien: '#'
Slider:
    image: slider1.png
SliderTitre: Sliders
