# Ce fichier contiens la config de base du serveur

Infos: 
  -
    message: "Image de démo à modifier dans votre panel CraftMyWebsite !"
    image: "miniature-demo-1.jpg"
    lien: "#"
  -
    message: "Image de démo à modifier dans votre panel CraftMyWebsite !"
    image: "miniature-demo-1.jpg"
    lien: "#"
  -
    message: "Image de démo à modifier dans votre panel CraftMyWebsite !"
    image: "miniature-demo-1.jpg"
    lien: "#"
Slider: 
    image: "slider1.png"
SliderTitre: "Sliders"
