#Ce fichier contiens la config de base du serveur---
installation: true
licence: free-craftmywebsite.fr
General:
    url: https://cmw-developpement.tk/
    name: CMW_TEST
    theme: default
    themeOption: bootstrap
    description: cmw test
    bgType: 0
    permsPlugin: groupManager
    permsWorld: world
    ipTexte: play.epicube.fr
    ip: play.epicube.fr
    port: "25565"
    createur: Créateur
DataBase:
    dbAdress: localhost
    dbName: cmw
    dbUser: phpmyadmin
    dbPassword: ic82yD53R4
    dbPort: "3306"
Payement:
    paypal: true
    mcgpass: true
    mcgpass_id: "1734"
    mcgpass_idSite: "137"
    paypalUser: ""
    paypalPass: ""
    paypalSignature: ""
    paypalEmail: curvalle.florent@gmail.com
    paypalMethodeAPI: "1"
color:
    main: '#ff0080'
    hover: '#ff00ff'
    focus: '#ff80c0'