# Ce fichier contiens la config de base du serveur

MenuTexte:
  - "Accueil"
  - "Serveur"
  - "Boutique"
  - "Support"
  - "Voter"
  - "Forum"
MenuLien:
  - "index.php"
  - "#"
  - "?&page=boutique"
  - "?&page=support"
  - "?&page=voter"
  - "?page=forum"
MenuListeDeroulante:
  "Serveur":
    - "Ban-List"
    - "Chat"
MenuListeDeroulanteLien:
  "Serveur":
    - "?page=banlist"
    - "?page=chat"