#Ce fichier contiens la config de base du serveur
MenuTexte:
  - "Accueil"
  - "Serveur"
  - "Boutique"
  - "Support"
  - "Voter"
  - "Forum"
  - "test"
MenuLien:
  - "index.php"
  - "#"
  - "?&page=boutique"
  - "?&page=support"
  - "?&page=voter"
  - "?page=forum"
  - "http://bite.ftr"
MenuListeDeroulante:
  "Serveur":
    - "Ban-List"
MenuListeDeroulanteLien:
  "Serveur":
    - "?page=banlist"